# Config file for the SystemAnalyzer.
# This way we can easily change the paths, and systems without having to clutter the notebook with this information.
paths:
  system: "1wave_9010"
  output: "output"
  replicate: "rep2"
  calm: "CALM"
  calm_fit: "CALM_fit"

files:
  xtc: "fixed.xtc"
  pdb: "fixed.pdb"
  tpr: "fixed.tpr"
  dim: "dimensions.csv"
  leaflets: "leaflets.ndx"
  densmapBG: "densmapBackground.dat"
  densmapCDL0: "densmapCDL.dat"
  densmapPOPC: "densmapPOPC.dat"

beads:
  PO4_1: "resname CDL0 and name PO41"
  PO4_2: "resname CDL0 and name PO42"
  NC3: "resname POPC and name NC3"