# Config file for the SystemAnalyzer.
# This way we can easily change the paths, and systems without having to clutter the notebook with this information.
paths:
  system: "1wave_9010"
  rep: "output/rep2"
  calm: "CALM"

files:
  xtc: "fixed.xtc"
  pdb: "fixed.pdb"
  tpr: "fixed.tpr"
  dim: "dimensions.csv"
  leaflets: "leaflets.ndx"

selections:
  PO4_1: "resname CDL0 and name PO41"
  PO4_2: "resname CDL0 and name PO42"
  NC3: "resname POPC and name NC3"